name: coach_finder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  flutter_secure_storage: ^9.0.0
  reactive_forms: ^16.1.1
  modal_bottom_sheet: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  assets:
    - assets/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Bold.ttf
        - asset: fonts/RobotoMono-BoldItalic.ttf
        - asset: fonts/RobotoMono-ExtraLight.ttf
        - asset: fonts/RobotoMono-ExtraLightItalic.ttf
        - asset: fonts/RobotoMono-Italic.ttf
        - asset: fonts/RobotoMono-Light.ttf
        - asset: fonts/RobotoMono-LightItalic.ttf
        - asset: fonts/RobotoMono-Medium.ttf
        - asset: fonts/RobotoMono-MediumItalic.ttf
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-SemiBold.ttf
        - asset: fonts/RobotoMono-SemiBoldItalic.ttf
        - asset: fonts/RobotoMono-Thin.ttf
        - asset: fonts/RobotoMono-ThinItalic.ttf

  uses-material-design: true